version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
    volumes:
      - ./backups/:/mnt/backups/
      - es-data:/usr/share/elasticsearch/data/
    environment:
      - cluster.name=elasticsearch
      - network.host=0.0.0.0
      - path.repo=/mnt/backups
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - "XPACK_SECURITY_ENABLED=false"
      - discovery.type=single-node
      - xpack.ml.enabled=false
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false
    ports:
      - "9200:9200" # expose container port for local dev
    healthcheck:
      test: "curl http://elasticsearch:9200"
      interval: "1s"
      timeout: "3s"
      retries: 60

volumes:
  es-data: